- .eslintrc.json
- .gitignore
- Dockerfile
- README.md
- package.json
This pull request adds Docker support to the project, allowing for an easier setup and deployment process. The changes made include:
1. Updating `.eslintrc.json` to disable certain rules that were causing the build to fail.
2. Adding the `NEXTAUTH_SECRET` and `OPENAI_API_KEY` environment variables to the `.env` file.
3. Modifying `package.json` to disable lint during the build process.
4. Updating `.gitignore` to ignore the `/db` directory.
5. Updating `README.md` with instructions on how to run the app with Docker.
By adding Docker support, users can now easily build and run the application within a Docker container. This simplifies the setup process and ensures a consistent environment across different machines. Additionally, data persistence is maintained using a mounted volume for the …
> Add Docker support for easier setup and deployment

- src/components/ChatWindow.tsx
In an effort to quickly address the need noted in [issue 18](https://github.com/reworkd/AgentGPT/issues/18), I added a quick button for copying the inner text of the run to the clipboard. In this way, it can quickly be used in whatever application desired without spending a lot of effort on specific use cases at the moment.
> [Issue-18] Add button to copy text to clipboard

- README.md
Fixes #7 
Add `cd` instruction to have the complete installation steps in the README file.
> add cd in instructions

- src/components/Drawer.tsx
Fixes #68 
- Isomorphic DrawerItem to be either a clickable button or anchor
- Converted DrawerItem `div` into a `button` for WCAG purposes and a11y best practices for a tabbable DOM
UIX;
Tabbable works as it gets the focus style;
> Bugfix for #68 

- src/components/AutonomousAgent.ts
- src/components/Input.tsx
- src/components/SettingsDialog.tsx
- src/pages/api/chain.ts
- src/pages/api/create.ts
- src/pages/api/execute.ts
- src/pages/index.tsx
- src/utils/chain.ts
**Description:**
allow user to input custom model name
> feat(#33): implement model input

- src/pages/index.tsx
When a user has no tasks, instead of displaying nothing it shows "0" so I converted the check into a boolean
> fix: remove rogue zero

- Dockerfile
- setup.sh
Fixes an issue with the `NODE_ENV` environment variable defaulting to `production` during the Docker build process, which was causing problems with the `./setup.sh --docker` command.
Fixes #147.
> Fix `./setup.sh --docker` build failure

- package-lock.json
- package.json
- src/components/Combobox.tsx
- src/components/Input.tsx
- src/components/SettingsDialog.tsx
- src/utils/helpers.ts
**Description:**
Several improvements to combobox (previously named dropdown)
1. Use Headless UI
a.  combobox is now accessible
b.  combobox queries can now autocomplete
c. UX is now more intuitive (will only display the full list if the chevron is clicked)
2. minor refactor to Input component to make the code more dry (no longer repeating code in both input and combobox)
> feat: refactor combobox to make it more maintainable

- src/components/Input.tsx
- src/components/SettingsDialog.tsx
- src/pages/index.tsx
- Update - autofocus the first input element of the Settings Dialog component when component is shown (better UX).
- Small refactor to destructure props of `SettingsDialog` component inside of component (for better readability/maintainability) and creation of `SettingsDialogProps` interface (also for better readability/maintainability). Same done on InputProps.
> feat: auto focus on first input on app load

- setup.sh
- src/components/SettingsDialog.tsx
Added Key validation to the setup script.
The keys from open ai have 51 characters in total and are prefixed with "sk-".
So this regex captures that case ^sk-[a-zA-Z0-9]{48}$
I've also added the same check within the settingsDialog component & It won't save an API key unless it has a valid format.
It will also notify the user with an alert.
> Key validation

- src/components/Input.tsx
- src/components/Label.tsx
- src/pages/index.tsx
- Added a bigger UI for `Goal` input using the `textarea` HTML element.
- As a `textarea` is used, users can now enter goals in multiple lines by pressing the `Shift + Enter` keys to create a new line.
- Input.tsx
- Label.tsx
**Larger Screens**
**Mobile**
This fixes #232
> feat: [#232] Added a bigger UI for Goal input

- src/components/Dialog.tsx
when i copy my key in the modal, i found some bug. when i mouse down in the modal and mouseup ouside the modal,the modal will close. like the video show. I fixed it in this pr.
https://user-images.githubusercontent.com/14836590/233037939-4212cd0f-9549-41d2-9e3c-fbd2eeb01325.mov
> fix: fix close Modal incorrectly

- __tests__/whitespace.test.ts
- src/pages/index.tsx
- src/utils/whitespace.ts
> 🐛 Add Validation For Name & Goal

- prisma/schema.prisma
With the current version of Prisma (4.9.0), I believe we do not need to add `ReferentialIntegrity` in previewFeatures. 
And
> chore: remove unnecessary annotations & add indices to prisma schema

- src/components/ChatWindow.tsx
This pull request implements a fix for a TypeError that occurs when trying to use the navigator.clipboard.writeText method in Microsoft Edge, which may not have support for the Clipboard API in some versions. To resolve this issue, we have added a check for the existence of the navigator.clipboard object before attempting to use the writeText method. In cases where the Clipboard API is not supported, we have provided a fallback method for copying text to the clipboard using a temporary textarea element.
This fix ensures compatibility with Microsoft Edge and other browsers that may have limited or no support for the Clipboard API, preventing the TypeError from occurring and enabling the text copy functionality to work as expected.
> fix TypeError: Cannot read properties of undefined (reading 'writeText')

- src/pages/index.tsx
ref: https://github.com/facebook/react/issues/11538#issuecomment-390386520
fixed: #212 
Additional Question) There's [another workaround](https://github.com/facebook/react/issues/11538#issuecomment-417504600) that if removeChild will cause error keep child node and make not crush. Is below code useful to this situation?
```javascript
if (typeof Node === 'function' && Node.prototype) {
const originalRemoveChild = Node.prototype.removeChild;
Node.prototype.removeChild = function(child) {
if (child.parentNode !== this) {
if (console) {
console.error('Cannot remove a child from a different parent', child, this);
}
return child;
}
return originalRemoveChild.apply(this, arguments);
}
const originalInsertBefore = Node.prototype.insertBefore;
Node.prototype.insertBefore = function(newNode, …
```
> 🐛  Catch removeChild error use semantic node instead of text node

- src/components/ChatWindow.tsx
- src/components/Dialog.tsx
- src/components/Drawer.tsx
- src/components/HelpDialog.tsx
- src/components/SettingsDialog.tsx
- src/components/SignInDialog.tsx
- src/components/SorryDialog.tsx
- src/pages/index.tsx
- Add a dialog for when web search is disabled
- Add a dialog for when users try to deploy without signing in
- Refactor settings dialog a bit
Note this is all frontend only
- In the case of web search, even if they hack to enable it, the backend won't support it
- In the case of deploying, even if they hack to deploy without signing in, we're no worse off than before
> Force auth frontend

- src/components/ChatWindow.tsx
- src/components/SettingsDialog.tsx
- src/components/Switch.tsx
**Description:**
No longer inside settings
> fix: move mode toggle out of settings

- src/components/Button.tsx
- src/components/ChatWindow.tsx
- src/components/TaskWindow.tsx
- src/pages/agent/index.tsx
- src/pages/index.tsx
The task window currently is only visible on screen size `xl` and above. This means mobile users will be void of a decent bit of app functionality. This PR does the following:
- Make TaskWindow always visible instead of only appearing when tasks are present
- Add a button group to the top of the page when screen size is lower than `xl`
- The button group controls which window is visible. This defaults to the chat window
> 📄 Add buttons to display TaskWindow on mobile

- next/Dockerfile
- next/entrypoint.sh
The `./next:/next/` volume binding in the `docker-compose.yml` file was overwriting the _DOS2UNIX_ fix done at the image build stage. Now, the `entrypoint.sh` is moved to the `/` directory to avoid the volume binding (causing the line ending overwrite).
Also, the dos2unix fix is run in the _entrypoint.sh_ to fix the `wait-for-db.sh` and `.env` files at runtime (for the same reason).
closes #511
> Fixed Dockerfile and entrypoint.sh to handle Windows line endings

- platform/reworkd_platform/tests/agent/agent/remove_task_prefix_test.py
I've noticed there are recurring tests that can be collected within one parametrized test function. Using parameterized for them would be beneficial for creating a clean test environment.
> 🐛 Use parametrize instead of creating replicated test functions

- platform/reworkd_platform/tests/agent/agent/extract_tasks_test.py
- platform/reworkd_platform/tests/agent/agent/real_task_filter_test.py
- platform/reworkd_platform/tests/agent/agent/remove_task_prefix_test.py
I've completed converting other parametrizable test functions as I did here: #591
> 🧪 Parametrize Tests

- next/tailwind.config.cjs
Resolves #747
**Description**: 
add color theming for dark mode (see [figma](https://www.figma.com/file/hBQdHjGlnESMcHXcaPn1lM/AgentGPT?type=design&node-id=168-2&t=b7JXtYxDqGd4HViO-0) for detail - ignore coloring for light)
> feat(#747): place colour theming into tailwind config

- platform/Dockerfile
This is the fix to (issue 850)[https://github.com/reworkd/AgentGPT/issues/850] which fails because it cannot find pkg-config on the docker image for platform.  It was a removed dependency in commit (30022a7).
> Re-adding required dependency that was removed in 'Sync repo' (30022a7)

- platform/Dockerfile
Ref:
https://github.com/reworkd/AgentGPT/issues/848
https://github.com/reworkd/AgentGPT/issues/850
> pkg-config: not found when `poetry install --only main`;

- README.md
**Issue: Difficulty with Initial Setup and Clarity**
Users are finding it challenging to get started due to unclear instructions. Some common hurdles include not knowing where the terminal is, how to access it, and what needs to be downloaded beforehand. Along with setup.bat changed to ./setup.bat
**Proposed Solution**
To improve the clarity and ease of the initial setup process, we could provide more detailed, step-by-step instructions with prerequisite downloads and how to access and use the terminal.
> ☝️ Update README.md

- next/src/components/console/ChatMessage.tsx
- next/src/components/console/MacWindowHeader.tsx
- next/src/components/console/MarkdownRenderer.tsx
- next/src/components/utils/helpers.tsx
> © copy button on top off header messages

- next/src/components/landing/Backing.tsx
- next/src/components/landing/Hero.tsx
-Adjusted styling of backing to appear like the one in Figma
- strictly adjusted styling nothing else
> 👈 Updated Backing for Hero Component 

- next/src/components/BannerBadge.tsx
- next/src/styles/globals.css
- Changed banner styling 
- Started on the pulsing 
- Unsure how to start the border glow train
- For some reason react icons don't have the PiStarFourFill the star on Figma
- Pulsing isn't rounded and bleeds pixels making a square look 
**Before:**
**After**
closes #912
> 912 banner badge glow in hero section

- next/src/components/NavLayout.tsx
- next/src/components/landing/Footer.tsx
relates to #938 
Text alignment isn't quite perfect but this can be addressed later
> 👟 Footer for landing page

- next/.husky/pre-commit
- next/entrypoint.sh
- next/prisma/useSqlite.sh
- next/wait-for-db.sh
- platform/entrypoint.sh
- setup.sh
In general, `#!/usr/bin/env bash` is considered better practice because it's more portable.
Bash is not always located at /bin/bash.
This will make the scripts work on systems, like the Linux dist NixOS
The readme instructions does not work on some systems. Like mine (NixOS).
By running `./setup.sh` as mentioned above
in
> > nixos-version --verbose         
>                 
> 22.11.20230629.c6643a9 (Raccoon)
Changes visible to users:
Internal changes:
> Fix shebang so shell scripts work on more systems

- cli/package-lock.json
- cli/package.json
- cli/src/helpers.js
- cli/src/questions/newEnvQuestions.js
This solution involves:
Issue: #892
> feat: Validate user API keys in CLI

- docker-compose.yml
This is to fix [this issue](https://github.com/reworkd/AgentGPT/issues/984).
A `services` `docs` was added, but the `Dockerfile` is not present in the `docs` directory.
> Fix/failed to read dockerfile/issue 984

- next/src/pages/index.tsx
- added the functionality to store agent data in the browser's local storage and retrieve it when returning to the login home page after login.
- Chosen to use the browser's localStorage API due to its simplicity and synchronicity.
https://github.com/reworkd/AgentGPT/issues/888
https://github.com/reworkd/AgentGPT/assets/56135840/792a85bd-daba-4928-9f9f-33fd947159c7
> ✨ Fixed Loss of Agent Data upon Login

- next/public/email-24x24.svg
- next/src/components/PrimaryButton.tsx
- next/src/components/TextButton.tsx
- next/src/components/landing/Hero.tsx
- next/src/ui/button.tsx
- next/tailwind.config.cjs
> feat(#1001): implement contact us and explore AI Agents buttons

- next/src/components/BannerBadge.tsx
- next/src/components/landing/Hero.tsx
- Added clsx 
- Adjusted the text to be aligned on the edges by using rem
- Made the text normal from thin (kinda liked the thin font let me know what you think)
> 🐼 Updated the gradient

- next/src/styles/globals.css
Without anti-aliasing
WIth anti-aliasing
> fix: apply anti-aliasing to text

- next/package-lock.json
- next/package.json
- next/src/components/Menu.tsx
- next/src/components/ThemeMenu.tsx
- next/src/components/WindowButton.tsx
- next/src/components/console/MacWindowHeader.tsx
- next/src/components/drawer/WorkflowSidebar.tsx
- next/src/components/pdf/PDFButton.tsx
- next/src/pages/workflow/[workflow].tsx
- next/src/services/graph-utils.ts
- next/src/services/workflow/node-block-definitions.ts
- The frontend block definitions will now have output fields
- We will display those fields in a drop down when a node is selected
- We figure out fields by doing a reverse BFS from the current node up the tree
> 🔥 Display block outputs in the frontend

- platform/pyproject.toml
- platform/reworkd_platform/services/kafka/consumers/base.py
- platform/reworkd_platform/services/kafka/producers/base.py
- platform/reworkd_platform/settings.py
- Allows devs to share a single kafka cluster
- In dev mode, you will only consume message you produce
- Each person on the cluster will be assinged thier own consumer group
- Messages will be skipped if it is not produced by your maching
- Each consumer group keeps track of its own oftset
> 🔧 Dynamic Consumer Groups

- next/src/components/workflow/AbstractNode.tsx
- next/src/components/workflow/BasicNode.tsx
- next/src/components/workflow/Flowchart.tsx
- next/src/components/workflow/IfNode.tsx
- next/src/hooks/useWorkflow.ts
- next/src/services/workflow/node-block-definitions.ts
- next/src/styles/globals.css
- next/src/types/workflow.ts
- Create a separate `IfNode` node type for react flow
- When there are multiple source or target handles, we must give them a unique id 
- Update handle styling
> ᛘ Frontend logic for the IfNode

- README.md
Add the links to the services will help people to know which services, precisely, they need to sign up for
> chore: add services links to readme

- next/src/pages/workflow/[workflow].tsx
- next/src/services/fetch-utils.ts
- next/src/services/workflow/workflowApi.ts
- window alert on successful save, else error alert (references specific error text)
> 🦺 FE error handling

- platform/reworkd_platform/schemas/workflow/blocks/agents/content_refresher_agent.py
- pass source metadata through content refresher agent (cite in-line on added information)
- modify `add_info()` prompt so result follows `target_content` format better
> 🌎 Pass source metadata through content refresher agent

- platform/reworkd_platform/schemas/workflow/blocks/agents/content_refresher_agent.py
- additional output on content refresher agent (bullet points of infos from each source)
- fix 'workflow failed: too much data' error (iterate and log new_infos rather than one-liner)
- make `competitors` input optional
> ✏️ Content agent bullet output

- next/src/components/workflow/Flowchart.tsx
- fixed 'node self-connection' bug
- if connect to block, don't open blockDialog
> 😈 Bug squash

- next/src/components/dialog/HelpDialog.tsx
- next/src/components/sidebar/links.tsx
fixes #1330 
Currently twitter icon was using `react-icons/fa` (fonts awesome 5)
Newer version is `react-icons/fa6` (fonts awesome 6)
New Preview -
> fix: update twitter logo to X

- cli/src/envGenerator.js
- platform/entrypoint.sh
Fixes #1332 
Context:
The mysql container was renamed in a big PR (#1327) and the env files were left out thus new setups fail
> fix: update db container name instances in env

- next/src/components/dialog/ToolsDialog.tsx
- platform/reworkd_platform/web/api/agent/tools/sidsearch.py
These changes make it so that, if the SID tool cannot find any relevant information, or if the tool experiences some other issue (e.g. expired token, network issues, etc.), the agent automatically falls back to a standard google search.
Also, alignment of buttons in the tool menu is fixed for the SID tool.
> In SID tool, fall back to normal search if no results are available

- docs/development/translations.mdx
Hey there :wave:
I was going through your documentation and noticed a small typo on the Translation page!
This PR simply fixes it.
Any feedback is welcome!
> docs: Fixes typo in the documentation about translations
