reworkd/AgentGPT

.env.example
README.md
src/env/schema.mjs
src/server/auth.ts

:wrench: Update documentation on environment variables

---

src/components/SettingsDialog.tsx

⭐ Describe how key is stored

---

src/components/ChatWindow.tsx

tackles #17 
- Display copy icon on hover
- displays the text "Copied!" when copied
- the text "Copied!" disappears after 2 seconds

[issue-17] Display Copy Icon on Message Hover

---

package-lock.json
package.json
src/components/ChatWindow.tsx
src/styles/globals.css

👩‍💻 Add markdown formatting

---

src/components/AutonomousAgent.ts
src/pages/api/chain.ts
src/pages/api/create.ts
src/utils/chain.ts

Use regex to filter bad tasks

---

README.md
package-lock.json
package.json

Description: 
Update README and package.json to specify node version requirement (>=16.8.0)

chore: specify node version in readme and package.json

---

src/components/AutonomousAgent.ts
src/pages/api/chain.ts
src/pages/api/create.ts
src/pages/api/execute.ts
src/pages/index.tsx
src/utils/chain.ts
src/utils/constants.ts
src/utils/interfaces.ts
src/utils/types.ts

Description: 
store interfaces, types and constants used by multiple files in one place to reduce change amplification

feat: add interfaces, types and constants file

---

src/components/Input.tsx
src/components/SettingsDialog.tsx

PR to fix bug #98 
bug fix output looks like this:-

added tailwind css class which fix the bug #98

---

.devcontainer/devcontainer.json
README.md

Adds GitHub Codespaces support for quick cloud-based development and ad-hoc deployment. 
See README.md for instructions.

Add GitHub Codespaces support

---

.devcontainer/devcontainer.json

This introduces several enhancements to the development container, including forwarding the Next.js server port, adding the ESLint extension, Docker (for debugging purposes), common-utils, and Git feature.
These improvements provide better debugging support and essential tools for developers.
Notably, these changes offer an improved experience for self-hosted Dev containers in accordance with the https://containers.dev specifications, ensuring a consistent development environment across different setups and not just Codespaces.
If you're interested in learning more about the added tools and features, check out https://containers.dev/features.

Enhance development container configuration with additional features and tools

---

src/components/Drawer.tsx
src/pages/index.tsx
src/styles/globals.css

💅 fix layout overflow

---

src/components/AutonomousAgent.ts
src/components/SettingsDialog.tsx
src/utils/constants.ts

1. Clarify API key requirement for GPT-4 
2. Highlight Explaination when GPT-4 is selected
3. Improve error message when Agent fails and GPT-4 model is selected

feat: improve explanation for GPT4 model requirement

---

src/components/ChatWindow.tsx
src/components/TaskWindow.tsx
src/pages/index.tsx

bug: improve task styling

---

README.md
docs/README.zh-HANS.md

Description:
Add Chinese translation for readme

feat: add chinese translation for ReadMe

---

.github/workflows/node.js.yml
prisma/schema.prisma
src/server/auth.ts

:bug: Enums not supported in SQLite

---

.devcontainer/devcontainer.json
.editorconfig
.vscode/extensions.json

Adds EditorConfig support to the project, which will help ensure consistent coding styles and formatting across different editors and IDEs used by contributors.
More information: https://editorconfig.org.

Add EditorConfig support

---

.vscode/launch.json

Added a VSCode launch.json for easy launching in Visual Source Code (also in Github Codespaces).

feat/add vscode launch.json

---

docs/README.zh-HANS.md
src/components/SettingsDialog.tsx

fix(#213): update temperature tooltip

---

src/components/Input.tsx
src/pages/index.tsx

- Pressing enter button to deploy agents feature added.
- pages/index.tsx
This cloes #231

feat: [#231] Press Enter key to deploy Agent

---

README.md
docs/README.hu-Cs4K1Sr4C.md

- Hungarian translation of the main README.md
- Extended README.md with the badge and the link to the Hungarian translation of the main README.md

Hungarian translation of the main README.md

---

README.md
docs/README.hu-Cs4K1Sr4C.md
docs/README.zh-HANS.md

:bug: Fix discord link

---

src/env/schema.mjs

Ability to deploy projects to Vercel with one click

Ability to deploy projects to Vercel with one click

---

src/pages/index.tsx

bug: add trim when handle new goal and save

---

.eslintrc.json
src/components/SettingsDialog.tsx
src/hooks/useSettings.ts
src/pages/index.tsx

feat: Persist custom settings

---

src/components/Input.tsx

- The language combo box overlap issue is fixed.
This fixes #361

fix: [#361] Z-index issue in Settings

---

src/components/ChatWindow.tsx

This change modifies ChatWindow.tsx to render unordered and ordered lists properly by adding support for the corresponding HTML tags in the ReactMarkdown component.

Update ChatWindow.tsx ISSUE #295

---

src/hooks/useSettings.ts

fix: #428 
Only load settings form localStorage with customApiKey

fix: settings load

---

public/locales/en/chat.json
src/components/ChatWindow.tsx
src/components/LanguageCombobox.tsx
src/pages/index.tsx
src/utils/languages.ts
src/utils/prompts.ts

📃 Add examples to the front page and fix prompts

---

setup.sh

https://github.com/reworkd/AgentGPT/issues/508

Fix Invalid environment variables(NEXT_PUBLIC_BACKEND_URL: Required)

---

docs/docs/development/prompts.md
platform/reworkd_platform/web/api/agent/prompts.py

- Adds documentation to prompts

💬 Update start agent prompt

---

.env.example
next/src/components/ChatWindow.tsx
next/src/components/Menu.tsx
next/src/components/WindowButton.tsx

💅 Update styling for chat window buttons

---

docs/docs/faq.md

Update faq.md to correct Typo error

Update faq.md to correct Typo error

---

next/src/components/AutonomousAgent.ts
next/src/components/LanguageCombobox.tsx
next/src/pages/index.tsx
next/src/services/agent-api.ts
next/src/utils/interfaces.ts
next/src/utils/types.ts
platform/reworkd_platform/settings.py
platform/reworkd_platform/web/api/agent/agent_service/agent_service.py
platform/reworkd_platform/web/api/agent/agent_service/agent_service_provider.py
platform/reworkd_platform/web/api/agent/agent_service/mock_agent_service.py
platform/reworkd_platform/web/api/agent/agent_service/open_ai_agent_service.py
platform/reworkd_platform/web/api/agent/model_settings.py
platform/reworkd_platform/web/api/agent/views.py

- refactors prompt languages so that prompt responses can be returned in multiple languages

🌎 MultiLanguage Prompt Support [Part 1]

---

.github/dependabot.yml

🤖 Update dependabot to use a monorepo

---

next/src/components/utils/helpers.tsx
next/src/server/auth/index.ts
next/src/services/agent/agent-api.ts
next/src/services/agent/autonomous-agent.ts
next/src/services/agent/message-service.ts
next/src/services/api-utils.ts
next/src/services/stream-utils.ts
next/src/types/errors.ts
next/src/types/next-auth.d.ts
next/src/utils/interfaces.ts
platform/reworkd_platform/db/base.py
platform/reworkd_platform/db/crud.py
platform/reworkd_platform/db/models/agent.py
platform/reworkd_platform/db/models/user.py
platform/reworkd_platform/schemas.py
platform/reworkd_platform/settings.py
platform/reworkd_platform/web/api/agent/dependancies.py
platform/reworkd_platform/web/api/agent/views.py
platform/reworkd_platform/web/api/dependencies.py
platform/reworkd_platform/web/api/error_handling.py
platform/reworkd_platform/web/api/errors.py
platform/reworkd_platform/web/api/monitoring/views.py

- Removed all max loop logic from JS
- Max loops are now controlled by python settings
- Ported a large part of auth code
- Local user now must sign in (fear not an error message is shown)
TODO:
- docs / cli improvement?

🥳 Improve max loops configuration

---

next/src/ui/combox.tsx

feat(#677): update dark mode for combo box

---

next/__tests__/message-service.test.ts
next/src/components/console/ChatMessage.tsx
next/src/components/console/ChatWindow.tsx
next/src/components/motions/FadeIn.tsx
next/src/components/utils/helpers.tsx
next/src/pages/agent/index.tsx
next/src/services/agent/agent-api.ts
next/src/services/agent/autonomous-agent.ts
next/src/services/agent/message-service.ts
next/src/stores/agentStore.ts
next/src/types/agentTypes.ts

- Remove thinking chat message type
- Add thinking state to agent store
- When ever the agent api is called, update the thinking state
- Display thinking state

🧠 Remove thinking chat message type

---

next/src/pages/settings.tsx
next/src/ui/input.tsx

- All users should now be able to see settings

🎨Advanced Settings Updates

---

next/src/components/landing/Hero.tsx
next/src/pages/secret-landing-page.tsx

Update title text to match landing page design
- Let me know if I should change the inline styling to use tailwind instead 
- Didn't add satoshi variable font as it looks different from the one in Figma

🦅 Header title sytling 

---

next/src/components/PrimaryButton.tsx

Updated the Styling of the Adjusted PrimaryButtonto go more with our new styling
-Does the same thing just looks better

Updated primary button

---

platform/poetry.lock
platform/pyproject.toml
platform/reworkd_platform/db/base.py
platform/reworkd_platform/db/models/agent.py
platform/reworkd_platform/db/models/user.py
platform/reworkd_platform/web/api/agent/dependancies.py
platform/reworkd_platform/web/api/dependencies.py

- Upgrading to use mapped_collumn instead worked like a charm. This is the standard for SLQA2.0. Prior we were using 1.4 syntax. Thanks chat gpt.

💪 Fix mypy <> sqla typing issues

---

next/src/components/FadingHr.tsx
next/src/layout/sidebar.tsx
next/src/styles/globals.css

feat(#768): update sidebar component theme

---

next/src/components/landing/ConnectorSection.tsx

-not sure if there is a better way to add spacing between the top and bottom for the integration with your & Entire Stack, i used <br/> but was too tight so I just split it up not sure what it's called in Tailwind

🦅 Updated title and subtitles for Connector Section

---

next/src/components/ThemeMenu.tsx

replace CgSun with FaSun to resolve hydration error in light mode

fix: resolve hydration error

---

next/src/components/Input.tsx
next/src/components/console/ChatWindow.tsx
next/src/components/console/ExampleAgents.tsx
next/src/components/console/SummarizeButton.tsx
next/src/pages/index.tsx
next/src/services/agent/autonomous-agent.ts
next/src/styles/globals.css

- Refactor out elements from ChatWindow and place them in index
- This is so they don't show up in the saved agents view

✨ Front page updates

---

next/src/components/Input.tsx
next/src/ui/combox.tsx
next/src/ui/input.tsx

- Fix hover animation and animation duration

✨ Update input styling

---

next/src/components/landing/Section.tsx
next/src/hooks/useMouseMovement.tsx
next/src/ui/highlight.tsx

- Did this so we can easily use this on other components, eg: buttons
- Done from 30k ft

♻️Refactor highlight logic

---

docs/essentials/roadmap.mdx
docs/mint.json
docs/other/philosophy.mdx

- Roadmap description
- Rename of nav anchors
- Changed the agentGPT icon

✨ Docs Formatting

---

docs/development/auth.mdx
docs/mint.json
next/src/components/landing/Hero.tsx
next/src/pages/landing-page.tsx

- Starter skeleton of the landing page

🦴 Skeleton landing page

---

next/src/components/BannerBadge.tsx
next/src/components/landing/Hero.tsx

- Changed the weight spacing tracking leading and got rid of icons on banner besides arrow.

💬 1003 update hero section text

---

next/src/components/landing/FooterLinks.tsx
next/src/components/landing/Hero.tsx

- Want to know what to do for the on hover, current I just took the hover that Joe made for the buttons under the hero title. 
- Maked a very basic list for the footer links started the status button. 
- Let me know oh how you would wan that ehover effects

👞 Footer Layout

---

next/src/components/workflow/WorkflowCard.tsx
next/src/pages/workflow/index.tsx
next/src/services/workflow/workflowApi.ts

Update workflow page styling to be consistent. Also add animation on open

✨ Workflow page updates

---

next/src/components/NavBar.tsx

✨ Navbar hover-highlight

---

next/src/components/BannerBadge.tsx
next/src/components/landing/Hero.tsx

- left chevron on landing page

Added left chevron on landing page 🔙

---

cli/src/index.js

Reverts reworkd/AgentGPT#1100
I'll take a look at this and fix, in the meantime I'll revert.

Revert "🐳 try catch for cli docker-compose"

---

next/src/components/workflow/nodes/BasicNode.tsx
next/src/services/workflow/node-block-definitions.ts
platform/reworkd_platform/schemas/workflow/blocks/conditions/ifcondition.py
platform/reworkd_platform/services/worker/execution_engine.py
platform/reworkd_platform/tests/workflow/test_execution_engine.py
platform/reworkd_platform/web/api/workflow/blocks/web/__init__.py

- Add basic web interaction agent block with types
- Fix if condition to correctly prune branch

🐛 Fix for if condition

---

next/src/components/Badge.tsx
next/src/components/drawer/DrawerItemButton.tsx
next/src/components/drawer/LeftSidebar.tsx
next/src/components/sidebar/AuthItem.tsx
next/src/components/sidebar/LinkItem.tsx
next/src/pages/_app.tsx

- Force dark mode across the app to avoid flicker
- Update sidebar to look a bit more sophisticated
**Before:**
**After:**

✨ Update sidebar styling

---

next/src/components/workflow/nodes/AbstractNode.tsx
next/src/components/workflow/nodes/BasicNode.tsx
next/src/components/workflow/nodes/IfNode.tsx
next/src/components/workflow/nodes/TriggerNode.tsx
next/src/services/workflow/node-block-definitions.ts

- Update node styling
- Fix selected node. Now if a node is selected, the border will still change during execution
- Refactor name / description into a common component 
- Note we're using the same icon for everything right now. This should be updated in the future
Before
After

✨ Update Node styling

---

next/src/components/workflow/BasicEdge.tsx
next/src/components/workflow/nodes/AbstractNode.tsx
next/src/hooks/useWorkflow.ts
next/src/types/workflow.ts
platform/reworkd_platform/services/worker/execution_engine.py
platform/reworkd_platform/services/worker/workflow_status.py

🚨Error status for workflows

---

next/src/components/drawer/WorkflowSidebar.tsx
next/src/components/workflow/Flowchart.tsx
next/src/hooks/useWorkflow.ts
next/src/pages/workflow/index.tsx

Quality of line improvements when creating new nodes for the workflow. Essentially, we want to create the node where we clicked
- Create node now takes in a `position` parameter for where to place the node once its created
- When you double click an area to create a node, it will store that click position and place the node there when it is added
- Edge is now animated even before save

✨ Workflow QOL

---

next/src/pages/workflow/index.tsx
next/src/ui/select.tsx

- The nav section is un-clickable because of pointer events. A bit annoying innit?
- No select items available message. Otherwise it "opens" to almost nothing

👈 Remove pointer events

---

next/src/components/workflow/Flowchart.tsx
next/src/components/workflow/nodes/AbstractNode.tsx
next/src/hooks/useWorkflow.ts
next/src/pages/workflow/index.tsx
next/src/services/workflow/node-block-definitions.ts
next/src/ui/select.tsx

- When a user creates a node from an edge drag, it will now ensure that node becomes connected via that edge
- Add different color for agents

🔥 Connect edge on drag create

---

next/src/pages/workflow/index.tsx

🪵 Log export

---

next/src/services/workflow/node-block-definitions.ts
platform/reworkd_platform/schemas/workflow/blocks/agents/content_refresher_agent.py
platform/reworkd_platform/tests/test_content_refresher_agent.py

- added input to content refresher agent to input keywords
- modified keyword prompt to search for unique keywords / appropriate amount based on # entered

🧩 Content refresh keyword input

---

next/src/components/drawer/WorkflowSidebar.tsx
next/src/ui/OauthIntegration.tsx
next/src/ui/combox.tsx
next/src/ui/dropzone.tsx
next/src/ui/input.tsx

- new slack button for new sidebar
- dropzone spiff
- output text
- other minor touchups (combo box, inputs)

🧽 Sidebar textfields

---

next/src/components/drawer/LogSidebar.tsx

- fix log sidebar overflow
- fix log sidebar button click

🌊 fix workflow sidebar

---

next/src/components/NavBar.tsx
next/src/pages/home.tsx

✨ Got rid of the try demo button

---

docs/essentials/FAQ.mdx

🐛 Fix typo in FAQ.mdx
